/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.isel.bytecodeparser;

import edu.handong.csee.isel.bytecodeparser.asm.BytecodeReader;

import java.util.ArrayList;
import java.util.Set;

public class Main {
    //input: 1) a Class file list path, 2) output path
    //output: Bytecode in text
    //(example) ../JavaFileExtractor/classFiles/deeplearning4j_files.txt ./RXJava

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        if(args.length != 2){
            System.err.println("input: 1) a Class file list path, 2) output path\n" +
                    "    (example) ../JavaFileExtractor/RXJava_files.txt ./RXJava\n");
            System.exit(-1);
        }

        String fileListPath = args[0];
        String outputPath = args[1];

        BytecodeReader br = new BytecodeReader(fileListPath);
        br.readClass(outputPath);

        System.out.println("Running Time (sec): " + ((System.currentTimeMillis() - start) / 1000));
    }
}
